### ISSUE TITLE
I don't understand how to use this 

### ISSUE THREAD

**Issue by Schweiger-Jacob** [delphiki/AirStatus#14]
I cloned the repo and folowed the steps but the terminal says main.py doesnt exist

**Comment by Schweiger-Jacob** [comment]
ok, I see that you have to cd into the Airstatus directory but when I run the python3 main.py output_file it says 

Traceback (most recent call last):
  File "/home/jacob/AirStatus/main.py", line 1, in <module>
    from bleak import discover
ModuleNotFoundError: No module named 'bleak'

**Comment by Schweiger-Jacob** [comment]
ok I see that you need to download bleak, I did and now I get this output 

/home/jacob/AirStatus/main.py:59: DeprecationWarning: There is no current event loop
  loop = get_event_loop()
/home/jacob/AirStatus/main.py:43: FutureWarning: The discover function will removed in a future version, use BleakScanner.discover instead.
  devices = await discover()

and it stays stuck on this

**Comment by Schweiger-Jacob** [comment]
I installed the older version of bleak instead and now theres less erros but it's still stuck at 

/home/jacob/AirStatus/main.py:59: DeprecationWarning: There is no current event loop
  loop = get_event_loop()

**Comment by mrsteve0924** [comment]
> 

now connect your airpods to your pc and you should see the output in the terminal

**Comment by mrsteve0924** [comment]
> devices = await discover()

now connect airpods and battery status should output to terminal

**Comment by olivertzeng** [comment]
> ok, I see that you have to cd into the Airstatus directory but when I run the python3 main.py output_file it says
> 
> Traceback (most recent call last): File "/home/jacob/AirStatus/main.py", line 1, in from bleak import discover ModuleNotFoundError: No module named 'bleak'

`pip3 install -r requirements.txt`

**Comment by olivertzeng** [comment]
I think the README surly needs more documentation though
