### ISSUE TITLE
Error?! When running the script.

### ISSUE THREAD

**Issue by Martin1134** [delphiki/AirStatus#18]
`Traceback (most recent call last):
  File "/home/martin/Scripts/AirStatus/main.py", line 147, in <module>
    run()
  File "/home/martin/Scripts/AirStatus/main.py", line 132, in run
    data = get_data()
  File "/home/martin/Scripts/AirStatus/main.py", line 68, in get_data
    raw = get_data_hex()
  File "/home/martin/Scripts/AirStatus/main.py", line 60, in get_data_hex
    a = loop.run_until_complete(get_device())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/martin/Scripts/AirStatus/main.py", line 43, in get_device
    devices = await discover()
  File "/home/martin/.local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 99, in discover
    async with cls(**kwargs) as scanner:
  File "/home/martin/.local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/home/martin/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 156, in start
    assert_reply(reply)
  File "/home/martin/.local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
`

Any advice?

**Comment by anlsergio** [comment]
Make sure to set `ControllerMode = dual` in `/etc/bluetooth/main.conf` then restart the bluetooth service `systemctl restart bluetooth`

**Comment by rus-99-pk** [comment]
> Make sure to set `ControllerMode = dual` in `/etc/bluetooth/main.conf` then restart the bluetooth service `sudo systemctl restart bluetooth`

Hello!

Thank you! It works for me.
