### ISSUE TITLE
no module named 'bleak'

### ISSUE THREAD

**Issue by goldentg** [delphiki/AirStatus#24]
```
python3 main.py /tmp/airstatus.out
Traceback (most recent call last):
  File "/home/evann/code/AirStatus/main.py", line 1, in <module>
    from bleak import discover
ModuleNotFoundError: No module named 'bleak'
```

**Comment by rico-vz** [comment]
> ```
> python3 main.py /tmp/airstatus.out
> Traceback (most recent call last):
>   File "/home/evann/code/AirStatus/main.py", line 1, in <module>
>     from bleak import discover
> ModuleNotFoundError: No module named 'bleak'
> ```

Try installing the requirements as sudo
